### ISSUE TITLE
Error:  No module named 'pysqlite3._sqlite3'

### ISSUE THREAD

**Issue by EzR1d3r** [coleifer/pysqlite3#25]
Hi, I have done all the steps twice to compile and install sqlite as a static lib, but I have the following error:
```
(venv) [easyrid3r@BRD-MINT pysqlite3]$ python
Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/easyrid3r/Projects/tests/test_sqlite/venv/pysqlite3/pysqlite3/__init__.py", line 23, in <module>
    from pysqlite3.dbapi2 import *
  File "/home/easyrid3r/Projects/tests/test_sqlite/venv/pysqlite3/pysqlite3/dbapi2.py", line 28, in <module>
    from pysqlite3._sqlite3 import *
ModuleNotFoundError: No module named 'pysqlite3._sqlite3'
```

**Comment by EzR1d3r** [comment]
I have found my mistake. I cloned this repo into the venv root directory. So 'import' tryed to import from repo dir instead of installed lib.
