### ISSUE TITLE
undefined symbol: _PyUnicode_EqualToASCIIString

### ISSUE THREAD

**Issue by josephernest** [coleifer/pysqlite3#28]
Hi, 
I followed the steps for the [static build detailed in the README](https://github.com/coleifer/pysqlite3#building-a-statically-linked-library) (I used the latest source from sqlite.org), everything worked sucessfully when doing:

    python3 setup.py build_static build install

It ended by:

```
Installed /usr/local/lib/python3.5/dist-packages/pysqlite3-0.4.6-py3.5-linux-x86_64.egg
Processing dependencies for pysqlite3==0.4.6
Finished processing dependencies for pysqlite3==0.4.6
```

Then when doing `python3` and `import pysqlite3`, I have:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pysqlite3-0.4.6-py3.5-linux-x86_64.egg/pysqlite3/__init__.py", line 23, in <module>
    from pysqlite3.dbapi2 import *
  File "/usr/local/lib/python3.5/dist-packages/pysqlite3-0.4.6-py3.5-linux-x86_64.egg/pysqlite3/dbapi2.py", line 28, in <module>
    from pysqlite3._sqlite3 import *
ImportError: /usr/local/lib/python3.5/dist-packages/pysqlite3-0.4.6-py3.5-linux-x86_64.egg/pysqlite3/_sqlite3.cpython-35m-x86_64-linux-gnu.so:
    undefined symbol: _PyUnicode_EqualToASCIIString
```

Is there something special to do to avoid this error?

**Comment by coleifer** [comment]
You need at least python 3.6.
